"""
Django settings for lawyerFinder project.

Generated by 'django-admin startproject' using Django 1.8.12.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os
import sys
import ConfigParser
reload(sys)
sys.setdefaultencoding("utf-8")
#from models import User

#/home/nelley/dj_pj_NL/lawyerFinder
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '0g26ebv$%$dig6oazgng2#p9d=#axmz*j0076+_8qnb7rc^jv^'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

#ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'debug_toolbar',
    'ckeditor',
    'ckeditor_uploader',
    'bootstrap3',
    'lawyerFinder',
    'accounts',
    'common',
    
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'lawyerFinder.middleware.session_controller_middleware.SessionControllerMiddleware'
    
)

#SESSION_COOKIE_AGE = 60 #second
#avoid datetime.datetime is not JSON serializable 
SESSION_SERIALIZER = 'django.contrib.sessions.serializers.PickleSerializer'
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

ROOT_URLCONF = 'lawyerFinder.urls'
AUTH_USER_MODEL = 'accounts.User'

MEDIA_ROOT = os.path.join(BASE_DIR, 'lawyerFinder/media')
MEDIA_URL = '/media/'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [ BASE_DIR + '/templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.core.context_processors.media',
            ],
        },
    },
]

WSGI_APPLICATION = 'lawyerFinder.wsgi.application'


SITE_URL = 'http://192.168.184.130:8000/'
#SITE_URL = 'http://10.39.5.152:8000/'
# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases
DATABASES = {
    'default': {
        #'ENGINE': 'django.db.backends.sqlite3',
        #'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
        'ENGINE': 'django.db.backends.mysql',
        
        'NAME': 'lawyerFinder',
        'USER': 'root',
        'PASSWORD': '',
        #'HOST': '192.168.1.104',
        #'HOST': '192.168.43.215',
        'HOST': '10.177.208.237',
        #'HOST': '10.137.134.110',
        
        
        #'NAME': 'namimoch_lawyerFinder',
        #'USER': 'namimoch_root',
        #'PASSWORD': '143Nami0016Mochi!',
        #'HOST': '50.87.248.134',
        
        'PORT': '3306',
        'OPTIONS': {
            'charset': 'utf8',
        },
    }
}


#LOGIN_REDIRECT_URL = '/accounts'

# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/
from django.utils.translation import ugettext_lazy as _

# python manage.py makemessages(generate xxxx.po file)
# python manage.py compilemessages(compile xxxx.po to mo file)
LANGUAGES = [
    ('ja', _('Japanease')),
    ('zh-TW', _('Traditional Chinese')),
]

LOCALE_PATHS = (
    os.path.join(BASE_DIR, 'locale'),
)

LANGUAGE_CODE = 'zh-TW'
#LANGUAGE_CODE = 'en'
TIME_ZONE = 'Asia/Taipei'
#translation system should be enabled
USE_I18N = True
USE_L10N = True

#timezone-aware by default or not
USE_TZ = False


# AWS SES
config = ConfigParser.ConfigParser()
config.read("/home/nelley/.aws/credentials.txt")
AWS_ACC_KEY_ID = config.get("DEFAULT","aws_access_key_id")
AWS_SEC_ACC_KEY = config.get("DEFAULT","aws_secret_access_key")


PROFILE_IMG_WIDTH = 150
PROFILE_IMG_HEIGHT = 200
PROFILE_IMG_SIZE = 4*1024*1024
PROFILE_IMG_VALID_FILETYPES = (
    'JPEG', 'GIF', 'PNG'
)

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

# for real enviroment(python manage.py collectstatic)
STATIC_ROOT = os.path.join(BASE_DIR, 'lawyerFinder/static')

STATIC_URL = '/static/'

# for general usage in dev
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, "projectstatic"),
)


LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'simple': {
            'format': '[%(asctime)s %(module)s] %(levelname)s: %(message)s'
        },
    },
    'handlers': {
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': True,
        },
    },
}
# form compitability with bootstrap 
from django.contrib.messages import constants as message_constants
MESSAGE_TAGS = {message_constants.DEBUG: 'debug',
                message_constants.INFO: 'info',
                message_constants.SUCCESS: 'success',
                message_constants.WARNING: 'warning',
                message_constants.ERROR: 'danger',}

# custom parameter(1*60(sec))
SESSION_FRONT_AGE = 60*60
SESSION_BACK_AGE = 1*60

# ckeditor settings
CKEDITOR_JQUERY_URL = 'lawyerFinder/js/jquery.js'
CKEDITOR_UPLOAD_PATH = "uploads/"
CKEDITOR_IMAGE_BACKEND = "pillow"

#CKEDITOR_ALLOW_NONIMAGE_FILES = False

CKEDITOR_CONFIGS = {
    'default': {
        'skin': 'office2013',
        'width':'100%',
        'height':'100%',
        'toolbar': (
            ['div', 'NewPage', 'Preview', '-', 'Templates'],
            ['Cut', 'Copy', 'Paste', 'PasteText', 'PasteFromWord', '-', '', ''],
            ['Undo', 'Redo', '-', 'Find', 'Replace', '-', 'SelectAll', 'RemoveFormat'],
            ['Bold', 'Italic', 'Underline', 'Strike', '-', 'Subscript', 'Superscript'],
            ['NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', 'Blockquote'],
            ['JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock'],
            ['Link', 'Unlink', 'Anchor'],
            ['Table', 'HorizontalRule', 'Smiley', 'SpecialChar', 'PageBreak'],
            ['Styles', 'Format', 'Font', 'FontSize'],
            ['TextColor', 'BGColor'],
            ['Maximize', 'ShowBlocks', '-'],
        ),
    }
}

